openapi: 3.0.0
info:
  title: Capstone
  version: 1.0.1
  description: 완전한 RESTful 원칙에 기반한 이메일 구독 등록, 해지 및 문제/답변/체점 API입니다.

tags:
  - name: Subscribe
    description: 이메일 구독 등록 및 해지
  - name: Answers
    description: 사용자 답변 제출 및 이력 조회
  - name: Auth
    description: 이메일 기반 인증 처리

paths:
  /api/subscribers:
    post:
      tags:
        - Subscribe
      summary: 구독 등록
      description: 사용자 이메일을 통해 새로운 구독자를 생성, 구독자가 선택한 카테고리들도 DB에 함께 저장. 카테고리는 문자열 배열 타입으로 전송
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
              properties:
                email:
                  type: string
                  format: email
                  example: user@example.com
                category:
                  type: array
                  format: array
                  example: ["Network", "Backend"]
      responses:
        '201':
          description: 구독 등록 완료
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 이메일이 성공적으로 등록되었습니다.
                  email:
                    type: string
                    example: user@example.com
        '409':
          description: 이미 등록된 이메일
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: 이미 구독 중인 이메일입니다.
        '500':
          description: 서버 오류
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: 서버 오류
    patch:
      tags:
        - Subscribe
      summary: 구독 해지
      description: 이메일 주소를 받아 구독을 해지합니다. (DB에서 이메일 삭제하지 않음)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
              properties:
                email:
                  type: string
                  format: email
                  example: user@example.com
      responses:
        '200':
          description: 구독 해지 처리 결과
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  email:
                    type: string
              examples:
                success:
                  summary: 정상적으로 구독이 해지된 경우
                  value:
                    message: 이메일 구독이 성공적으로 해지되었습니다.
                    email: user@example.com
                already_unsubscribed:
                  summary: 이미 구독이 해지된 경우
                  value:
                    message: 해당 이메일은 이미 구독 해지된 상태입니다.
                    email: user@example.com
        '404':
          description: 등록된 이메일이 없을 경우
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: 해당 이메일은 구독되어 있지 않습니다.
        '500':
          description: 서버 오류
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: 서버 오류

  /api/answers:
    post:
      tags:
        - Answers
      summary: 사용자 답변 제출
      description: 사용자가 받은 문제에 대한 답변을 제출합니다. 답변은 500자 이내로 받아야 하며 토큰 인증이 필요합니다.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - questionId
                - answer
              properties:
                questionId:
                  type: string
                  example: q001
                answer:
                  type: string
                  example: "function solution() { return true; }"
      responses:
        '200':
          description: 답변 제출 완료
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 답변 제출 완료
        '401':
          description: 인증 오류
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: 인증 오류
        '500':
          description: 서버 오류
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: 서버 오류

    get:
      tags:
        - Answers
      summary: 사용자 문제 풀이 결과 조회
      description: 사용자가 제출한 답변 이력을 조회합니다. 토큰으로 판별되며, 별도의 쿼리는 필요하지 않습니다.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: 문제 풀이 결과 목록
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    questionId:
                      type: string
                    answer:
                      type: string
                    score:
                      type: number
                    feedback:
                      type: string
        '401':
          description: 인증 오류
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: 인증 오류
        '500':
          description: 서버 오류
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: 서버 오류

  /api/answers/reveal:
    post:
      tags:
        - Answers
      summary: AI 기반 정답 요청 (모르겠어요 버튼)
      description: 사용자가 문제에 대한 정답을 모르겠을 때 Groq API를 통해 정답을 요청합니다. 인증이 필요합니다.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - questionId
              properties:
                questionId:
                  type: string
                  example: q001
      responses:
        '200':
          description: 정답 제공 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  questionId:
                    type: string
                    example: q001
                  answer:
                    type: string
                    example: "function solution() { return true; }"
        '401':
          description: 인증 오류
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: 인증 오류
        '404':
          description: 질문을 찾을 수 없음
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: 질문을 찾을 수 없습니다.
        '500':
          description: 정답 생성 실패 (Grok API 오류 등)
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: 정답 생성 중 오류가 발생했습니다.

  /api/answers/{answerId}/grade:
    post:
      tags:
        - Answers
      summary: 특정 답변에 대한 AI 채점 요청
      description: 사용자가 제출한 특정 답변에 대해 Grok API를 통해 AI 채점을 수행합니다. 채점 결과는 점수와 피드백으로 구성되며, 이후 오답노트에 활용됩니다.
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: answerId
          required: true
          schema:
            type: string
          description: 채점을 요청할 답변의 고유 ID
      responses:
        '200':
          description: AI 채점 결과 반환
          content:
            application/json:
              schema:
                type: object
                properties:
                  score:
                    type: number
                    example: 78
                  feedback:
                    type: object
                    properties:
                      wellDone:
                        type: string
                        example: "OSI 7계층의 구성 계층을 정확히 나열하였습니다."
                      improve:
                        type: string
                        example: "각 계층의 역할에 대한 간단한 설명이 있었다면 더 완성도 있는 답변이 되었을 것입니다."
                      mistake:
                        type: string
                        example: "계층 간 관계 설명이 누락되었습니다."
        '401':
          description: 인증 오류
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: 인증 오류
        '404':
          description: 답변을 찾을 수 없음
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: 해당 답변을 찾을 수 없습니다.
        '500':
          description: 서버 오류 또는 Grok API 오류
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: AI 채점 처리 중 오류가 발생했습니다.

  /api/answers/{questionId}/retry:
    post:
      tags:
        - Answers
      summary: 문제 다시 풀기
      description: 사용자가 이전에 푼 문제를 다시 선택하여 풀 수 있도록 기존 기록 위에 덮어씁니다. 토큰 인증이 필요합니다.
      security:
        - bearerAuth: []
      parameters:
        - name: questionId
          in: path
          required: true
          schema:
            type: string
          description: 다시 풀 문제의 ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                answer:
                  type: string
                  example: "function solution() { return true; }"
      responses:
        '200':
          description: 답변이 업데이트되었습니다.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 답변이 갱신되었습니다.
                  questionId:
                    type: string
                    example: q001
                  newAnswer:
                    type: string
                    example: "function solution() { return true; }"
        '404':
          description: 기존 문제 기록 없음
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: 해당 문제의 기존 답변이 존재하지 않습니다.
        '401':
          description: 인증 오류
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: 인증 오류
        '500':
          description: 서버 오류
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: 서버 오류.






  /api/auth/token:
    post:
      summary: 이메일 기반 임시 토큰 요청
      description: 등록된 이메일 주소로 질문을 받았을 때, 사용자가 '답변하기' 또는 '오답노트 보기' 버튼을 클릭하면 호출되는 API로, 해당 이메일에 대한 임시 토큰을 생성하여 인증에 사용됩니다.
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
              properties:
                email:
                  type: string
                  format: email
                  example: temp@temp.com
      responses:
        '200':
          description: 토큰 생성 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: a9f4b3c1d22e1cfa8b9
                  message:
                    type: string
                    example: 임시 토큰이 발급되었습니다.
        '400':
          description: 이메일 누락
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: 이메일이 누락되었습니다.
        '500':
          description: 서버 에러
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: 서버 오류

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: Token