openapi: 3.0.0
info:
  title: Test API
  version: 1.0.0-oas3
  
tags:
  - name: Subscribe
    description: 이메일 등록
  - name: Temp
    description: Temp api  
  
paths:
  /api/subscribe:
    post:
      tags:
      - Subscribe
      summary: 사용자 이메일 등록
      description: 이메일 주소를 통해 서비스 가입
      parameters:
        - name: email
          in: query
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  example: user@example.com
      responses:
        '201':
          description: 성공적으로 이메일 등록 완료
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "이메일이 성공적으로 등록되었습니다.등록하신 이메일을 확인해주세요."
                  email:
                    type: string
                    example: user@example.com
        '409':
          description: 이미 등록된 이메일일 경우
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "이미 구독중인 이메일 입니다."
        '500':
          description: "서버 에러"
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Server error"

